Display media content status
Iridescent-CM/technovation-app pull request #3288
Opened 2022-03-14 13:48 UTC by devkonrad

Display media content status

Changes:
modified: app/views/admin/participants/show.html.erb

Refs: https://github.com/Iridescent-CM/technovation-app/issues/3272

2022-03-14 22:16 UTC, shaunxp20 commented on app/views/admin/participants/show.html.erb
> +            <% if @account.student_profile&.media_consent&.consent_provided %>
`@account.student_profile&.` - it doesn't look like the `&` is necessary here, on line 203, we're already checking for a `student_account`

And another minor thing, it looks like the indentation is off for this entire `if` block. 🧐 😄

2022-03-14 22:19 UTC, shaunxp20 commented on app/views/admin/participants/show.html.erb
> +              Media Consent on file
It seems like this language might not quite be accurate - the conditional on line 206 checks for consent, not if it's "on file" or not. 🤔 😄

2022-03-15 11:08 UTC, devkonrad commented on app/views/admin/participants/show.html.erb
> +              Media Consent on file
I agree. @rsgonzal , is the purpose of this feature is check if the consent is provided?

2022-03-17 14:18 UTC, dboyer commented
Update after discussion with the program team. Ideally, they would like to know both if media consent has been given and the format it was given in (i.e. via the online form or via a paper form that someone emailed). So there are five possible states:

Agree to media consent via online form
Agree to media consent via paper form
Do not agree to media consent via online form
Do not agree to media consent via paper form
Has not completed media consent form

@devkonrad I realize this has expanded from the original plan for the issue. Please feel free to check in with someone if you need more details about how this could be implemented.

2022-03-18 15:29 UTC, devkonrad commented
As i could see, currently we have two params that controls the media_consent status inside de platform (consent_provided boolean flag and electronic_signature text info), so just por confirmation about the 5 status thar @dboyer mentioned:

Agree to media consent via online form => consent_provided is TRUE and electronic_signature is "Guardian Name"    
Agree to media consent via paper form => consent_provided is TRUE and electronic_signature is "ON FILE"
Do not agree to media consent via online form  => consent_provided is FALSE and electronic_signature is "Guardian Name"
Do not agree to media consent via paper form => consent_provided is FALSE and electronic_signature is "On File"
Has not completed media consent form  => The is no Media Content for the Student

Is that correct?

2022-03-28 19:20 UTC, viviancan commented
hey alex! Just did a quick QA locally! I think some of the wording/states are missing. Roxana will provide updated screens/details a little later. Thanks!

2022-03-28 19:20 UTC, viviancan requested changes
hey alex! Just did a quick QA locally! I think some of the wording/states are missing. Roxana will provide updated screens/details a little later. Thanks!

2022-03-28 19:52 UTC, devkonrad commented
> hey alex! Just did a quick QA locally! I think some of the wording/states are missing. Roxana will provide updated screens/details a little later. Thanks!

Hi, Vivian. Thanks for the feedback. I'll wait for @rsgonzal screen.

2022-03-31 17:24 UTC, closed without merging