Hides mentor age on public profile
Iridescent-CM/technovation-app pull request #3325
Opened 2022-03-29 14:34 UTC by devkonrad

Avoid to display mentors age when its accessed from mentors show profile.

Changes:
modified: app/views/profiles/_privileged_show.html.erb

Refs: https://github.com/Iridescent-CM/technovation-app/issues/3219
Discussion: https://github.com/Iridescent-CM/technovation-app/pull/328

2022-04-05 21:39 UTC, shaunxp20 commented on app/views/profiles/_privileged_show.html.erb
> +          <% if !account.mentor_profile.present? %>
Hmm, just curious if you have tested this with an account that has both a mentor and judge profile? Maybe it's okay, but just from looking at this code, I'm wondering if it would hide the age for judges for these cases? 🤔 😄

2022-04-06 12:20 UTC, devkonrad commented on app/views/profiles/_privileged_show.html.erb
> +          <% if !account.mentor_profile.present? %>
Thank you, for the tip @shaunxp20 ! I just tested with and account with mentor profile. I will add a Judge profile and test it. :)

2022-04-12 01:39 UTC, viviancan commented on app/views/profiles/_privileged_show.html.erb
> +          <% if !account.mentor_profile.present? %>
Following up on this!
I logged in as a mentor and then switched to a judge profile (for the same account) and did not see my age on either.

I did, however, catch a typo in `app/views/judge/profiles/rebrand/_basic.en.html.erb` line 10 says `age` and should be `Birthday` or `Date of Birth` or should this value be removed completely? @dboyer 
<img width="1316" alt="Screen Shot 2022-04-11 at 8 32 37 PM" src="https://user-images.githubusercontent.com/29210380/162861625-8ed1b9cf-f57e-43cc-b175-91d2daf53f9c.png">

2022-04-12 13:53 UTC, dboyer commented
We do not need to show age on the judge profile. It can be removed. 

The only place we have to have mentor and judge age is as a column we can add on the admin pages as shown in this screenshot. If it's available there, we're fine. 

<img width="1124" alt="Screen Shot 2022-04-12 at 9 52 49 AM" src="https://user-images.githubusercontent.com/516764/162977999-0c80f117-645c-4246-8df8-40072c581bd3.png">

2022-04-12 14:37 UTC, viviancan requested changes
Thanks for the work on this one, Alex! Please make the heading change on the Judge profile from `Age` to `Birthdate` as referenced in this comment 
https://github.com/Iridescent-CM/technovation-app/pull/3325#issuecomment-1096807479
Ty!!

2022-04-12 16:19 UTC, devkonrad commented
> Thanks for the work on this one, Alex! Please make the heading change on the Judge profile from `Age` to `Birthdate` as referenced in this comment [#3325 (comment)](https://github.com/Iridescent-CM/technovation-app/pull/3325#issuecomment-1096807479) Ty!!

Changes done! :)

2022-04-13 16:53 UTC, shaunxp20 commented on app/views/profiles/_privileged_show.html.erb
> +          <% if !account.mentor_profile.present? %>
> Following up on this! I logged in as a mentor and then switched to a judge profile (for the same account) and did not see my age on either.

Ah, I guess this makes sense - the requirements were to just to hide the age for mentors, but we're hiding it for judges as well - it doesn't make sense to hide it for one but not the other since since they can just toggle between the two profile types.

2022-04-13 16:54 UTC, shaunxp20 approved these changes
Thanks Alex! 👍 🙌

2022-04-13 18:07 UTC, merged