Add data limit according to platform
Iridescent-CM/technovation-app pull request #3412
Opened 2022-05-09 13:12 UTC by devkonrad

Ads data constraint according to platform, for URLs and other fields 

Changes:
modified: app/models/team_submission.rb

Refs: https://github.com/Iridescent-CM/technovation-app/issues/3372

2022-05-12 17:45 UTC, devkonrad commented
As discussed with @dboyer the "App Inventor Name" need to raise an error when its filled and we select "thunkable" as platform.

2022-05-19 20:04 UTC, devkonrad commented
> Ads data constraint according to platform, for URLs and other fields
> 
> Changes: modified: app/models/team_submission.rb
> 
> Refs: #3372

**QA Test Steps:**
_Enter to edit team submission page (on admin)_
1 - When develop platform changed to thunkable:
	- If you try to fill de App Inventor Name you will get an error
	- If you try to save without Thunkable URL you will get an error
2 - When develop platform changed to thunkable:
	- If you try to save with a Thunkable URL you will get an error
3 - If you try to save invalid URLs value on Demo video Link you will get an error
4 - If you try to save invalid URLs value on Pitch video Link you will get an error

2022-05-20 19:58 UTC, viviancan commented on app/models/team_submission.rb
> +  def padronize_url( url )
Hey Alex! Thanks for all the work on this one! 

It looks like this method name is in Portuguese (padronize). Could you update it to the English equivalent maybe something along the lines of `standardize_url` or something similar, in order to keep the consistency with English naming throughout the application?

2022-05-20 20:28 UTC, viviancan requested changes
Hi Alex, I left a few followup notes on the issue #3372. I had a few issues with editing a submission.

2022-05-20 21:53 UTC, devkonrad commented
> Hi Alex, I left a few followup notes on the issue #3372. I had a few issues with editing a submission.

Hi, Vivian! I answer your question about the validation here https://github.com/Iridescent-CM/technovation-app/issues/3372 . I just remain the validation that was use, but we can impove that if needed. :)

2022-05-24 14:45 UTC, viviancan commented on app/validators/thunkable_share_url_validator.rb
> -    if !value.match(/^https?:\/\/x.thunkable.com\/projects\/.+$/)
The "project" version is actually correct here! Sry about the confusion Alex!

2022-05-24 14:47 UTC, viviancan requested changes
Hi Alex, thanks for tackling this 👍 After verifying w/ deb this morning, I realized I misunderstood the requirement for the the thinkable url this morning. The original version with "project" is actually the correct version of the link we are accepting now - not the version with "copy". The change will have to be reverted back to the original URL that includes "project" - I think  in file `app/validators/thunkable_share_url_validator.rb` and the spec file.

2022-05-24 18:26 UTC, viviancan requested changes
Hey Alex, LGTM! Tested it locally and it is working as expected.

The only thing is on `def standardize_url( url )` there is extra whitespace around `url`.

2022-05-24 18:32 UTC, devkonrad commented
> Hey Alex, LGTM! Tested it locally and it is working as expected.
> 
> The only thing is on `def standardize_url( url )` there is extra whitespace around `url`.

Great, @viviancan! Thanks for the review. I will fix it and merge to QA. :)

2022-05-25 15:59 UTC, dboyer commented
@devkonrad Feel free to merge this to QA if it's just reverting the previous change.

2022-05-25 16:21 UTC, devkonrad commented
> @devkonrad Feel free to merge this to QA if it's just reverting the previous change.

Great. Doing that. :)

2022-05-25 16:26 UTC, merged