Updates home page splash for 'open for judges' version
Iridescent-CM/technovation-app pull request #3416
Opened 2022-05-11 14:09 UTC by devkonrad

Updates home page splash for 'open for judges' version

Changes:
modified:  app/views/application/_open_judge_splash.en.html.erb
modified:  app/views/public/dashboards/show.en.html.erb
modified:  spec/features/admin/off_season_splash_spec.rb

Refs: https://github.com/Iridescent-CM/technovation-app/issues/3413

2022-05-12 17:36 UTC, devkonrad commented
As siscussed with @dboyer (just to register) we need to do this changes:
- [ ] Remove the sign-up link (the words after login)
- [ ] Link "Registration is currently open for judges" to https://my.technovationchallenge.org/signup#/
- [ ] Link the word log-in to https://my.technovationchallenge.org/login

2022-05-12 21:13 UTC, shaunxp20 commented on app/views/public/dashboards/show.en.html.erb
> +      <%= render 'open_judge_splash' %>
The name of this new partial is popping out to me, I wonder if it can be named better, some suggestions: `judging_season_splash` or `judging_open_splash`. 🤔 😄

2022-05-12 21:35 UTC, viviancan commented on app/views/public/dashboards/show.en.html.erb
> +      <%= render 'open_judge_splash' %>
+1 here - I like the `judging_open_splash`

2022-05-13 12:17 UTC, devkonrad commented on app/views/public/dashboards/show.en.html.erb
> +      <%= render 'open_judge_splash' %>
Thank you @viviancan and @shaunxp20 for the review i'll proceed with the rename suggestion! :)

2022-05-13 12:18 UTC, devkonrad commented
> I left a clarifying question/comment on the ticket for Deb. When reviewing this locally, it is unclear that the text "Registration is currently open for judges" is actually a link to the registration page. This may be confusing, especially given recent feedback about this page.
> 
> I will wait to approve until a response from Deb. Otherwise, this looks great to me. Thanks for handling this one, Alex +1

Thanks, @viviancan. Meanwhile i'll do the other suggestion changes.

2022-05-16 18:08 UTC, viviancan commented on app/views/application/_judging_open_splash.en.html.erb
> +  Thank you for your interest in Technovation Girls. Register <%= link_to "here", "https://my.technovationchallenge.org/signup#/" %> to judge projects.
I would recommend using the `signup_path, data: { turbolinks: false }` so the signup link is not hard coded here.

2022-05-16 18:09 UTC, viviancan commented on app/views/application/_judging_open_splash.en.html.erb
> +    <%= link_to "log-in", "https://my.technovationchallenge.org/login" %> and review their existing projects.
Same here, I would recommend using the login path ` login_path, data: { turbolinks: false }`

2022-05-16 18:10 UTC, viviancan requested changes
Hey Alex, thanks for tackling this one! I would update the links so they are not hardcoded! Besides that, the changes look good 👍

2022-05-16 18:27 UTC, devkonrad commented on app/views/application/_judging_open_splash.en.html.erb
> +    <%= link_to "log-in", "https://my.technovationchallenge.org/login" %> and review their existing projects.
Great tip, Vivian! Thank you!

2022-05-16 19:15 UTC, viviancan approved these changes
Looks good, thx Alex 💯

2022-05-16 21:42 UTC, merged