Move project page link to admin submission page
Iridescent-CM/technovation-app pull request #3433
Opened 2022-05-18 14:01 UTC by devkonrad

Move project page link to admin submission page

Changes:
modified: app/data_grids/scored_submissions_grid.rb
modified: app/data_grids/submissions_grid.rb

Refs: https://github.com/Iridescent-CM/technovation-app/issues/3417

2022-05-19 14:35 UTC, viviancan requested changes
Please view the comment from Deb in #3417 for the updated changes! Thx!

2022-05-19 14:40 UTC, devkonrad commented
> Please view the comment from Deb in #3417 for the updated changes! Thx!

Thanks vivian. Just fix it! :)

2022-05-19 15:35 UTC, devkonrad commented
> Thanks for the changes, Alex!
> 
> I'm not 100% sure what is going on, but with the "export csv" option, the project page link is not part of the csv file! This should be addressed before merging to QA. Thanks!

Thamks for the catch, @viviancan! I will toake a look here :)

2022-05-20 16:53 UTC, devkonrad commented on app/data_grids/submissions_grid.rb
> +    "https://my.technovationchallenge.org#{url_helper.project_path(sub)}"
I put the URL encoded, because I couldn't find a way to put the dynamics in the csv. Since the request object is unavailable (if anyone knows how to do it dynamically, I'd appreciate it :))

2022-05-20 16:55 UTC, devkonrad commented
> Thanks for the changes, Alex!
> 
> I'm not 100% sure what is going on, but with the "export csv" option, the project page link is not part of the csv file! This should be addressed before merging to QA. Thanks!
I updated the PR and fixed this thing. :)

2022-05-20 19:58 UTC, shaunxp20 commented on app/data_grids/submissions_grid.rb
> +    "https://my.technovationchallenge.org#{url_helper.project_path(sub)}"
Try this to see if this is what we want:

```
column :project_page, html: false do |submission|
  Rails.application.routes.url_helpers.url_for(controller: "projects", action: "show", id: submission)
end
```

2022-05-20 22:01 UTC, devkonrad commented on app/data_grids/submissions_grid.rb
> +    "https://my.technovationchallenge.org#{url_helper.project_path(sub)}"
> Try this to see if this is what we want:
> 
> ```
> column :project_page, html: false do |submission|
>   Rails.application.routes.url_helpers.url_for(controller: "projects", action: "show", id: submission)
> end
> ```

Thanks, @shaunxp20 ! This works perfectly!

2022-05-23 18:51 UTC, viviancan approved these changes
Verifying that I was able to successfully export the submissions csv and the project page URL was there! Thx Alex

2022-05-23 19:46 UTC, merged