Updates Judge Recusal Box Style
Iridescent-CM/technovation-app pull request #3452
Opened 2022-05-30 14:53 UTC by devkonrad

Updates Judge Recusal Box Style

Changes:
modified: app/javascript/judge/scores/JudgeRecusalPopup.vue

Sample of the new box style:
![recusal-popup](https://user-images.githubusercontent.com/99268176/171017414-a0c22b76-b1c9-40ca-a309-c9e4e402d5da.png)

Refs: https://github.com/Iridescent-CM/technovation-app/issues/3409

2022-06-01 15:28 UTC, dboyer commented
Completed a functionality/style review and confirmed this is ready for code review @viviancan

2022-06-06 23:22 UTC, viviancan requested changes
I just left a follow up comment for Deb regarding the styling! I will wait for confirmation before the approval. Thx, Alex 💯 

The other thing I noticed is that the font for the recusal options seems to follow the older styling. Not sure if we want to update that 🤔

2022-06-07 13:24 UTC, viviancan commented on app/javascript/judge/scores/JudgeRecusalPopup.vue
> +        customClass: 'tw-green-btn'
This custom class of `tw-green-btn` is causing the entire modal to turn green :)

2022-06-07 14:06 UTC, devkonrad commented
> I just left a follow up comment for Deb regarding the styling! I will wait for confirmation before the approval. Thx, Alex 💯 
> 
> The other thing I noticed is that the font for the recusal options seems to follow the older styling. Not sure if we want to update that 🤔 

Thanks, @viviancan . Im going to take a look in these points. 😉

2022-06-08 15:35 UTC, devkonrad commented on app/javascript/judge/scores/JudgeRecusalPopup.vue
> +        customClass: 'tw-green-btn'
Thanks for the catch, @viviancan ! The bug was fixed! :)

2022-06-09 18:18 UTC, viviancan approved these changes
Did not pull down again! LGTM!

2022-06-09 18:22 UTC, devkonrad commented
> Did not pull down again! LGTM!

Thanks for the review, @viviancan! Im going to merge it! :)

2022-06-09 18:54 UTC, merged