Rebrand Judge Dashboard Inbetween Rounds
Iridescent-CM/technovation-app pull request #3479
Opened 2022-06-13 12:38 UTC by devkonrad

Rebrand Judge Dashboard Inbetween Rounds

Changes:
modified: app/views/judge/dashboards/onboarded/_between_rounds.en.html.erb

Refs: https://github.com/Iridescent-CM/technovation-app/issues/3466

2022-06-14 13:23 UTC, viviancan commented on app/views/judge/dashboards/onboarded/_between_rounds.en.html.erb
> +  <h2 class="text-base text-energetic-blue font-semibold tracking-wide uppercase">
This is not a blocker, but I am interested in QA feedback, with the `text-base` class the headings look smaller than the following context. I wonder if a large text class should be used like `text-lg` or `text-xl`?

2022-06-14 13:25 UTC, viviancan commented on app/views/judge/dashboards/onboarded/_between_rounds.en.html.erb
> +    View our <a href="https://technovationchallenge.org/judge-resources/" target="_blank">Judge Resource page</a> for more information.
We have a class for tags `tw-link` and it will change the link to energetic blue and on hover the text will change to magenta

2022-06-14 13:29 UTC, viviancan requested changes
Looks good to me locally! I left a few comments to consider before you merge to QA! We also need to deploy today, so please wait until the deployment is complete before you merge :) Thanks Alex!

2022-06-14 18:05 UTC, devkonrad commented on app/views/judge/dashboards/onboarded/_between_rounds.en.html.erb
> +    that will be finalists in our online World Summit event in August of 2022!
Thats a good idea, I just dont know if the event occurs on August every year. But nevertheless the dynamic year is a good thing to do. :)

2022-06-14 18:14 UTC, devkonrad commented on app/views/judge/dashboards/onboarded/_between_rounds.en.html.erb
> +  <h2 class="text-base text-energetic-blue font-semibold tracking-wide uppercase">
Changed it to text-lg instead and it looks better (in my opinion).

2022-06-15 17:43 UTC, viviancan approved these changes
Did not pull down the updates, looks good to me! Thanks Alex 💯

2022-06-15 19:57 UTC, devkonrad commented
> Did not pull down the updates, looks good to me! Thanks Alex 100

Thanks, @viviancan! Mergin into QA! :)

2022-06-15 23:17 UTC, merged