Rebrands the passowrd reset screen
Iridescent-CM/technovation-app pull request #3601
Opened 2022-08-23 11:14 UTC by devkonrad

This PR rebrands the Reset Pasword Screen.

![Captura de tela de 2022-08-23 08-13-28](https://user-images.githubusercontent.com/99268176/186144247-c6a163ed-3f1a-4824-becd-879caec66232.png)

Refs.: #3578

2022-08-23 13:25 UTC, dboyer commented
@devkonrad Looks good! Could you check if the font size on the button text is the same font size as the button text on the sign in and register pages? I'd like them to be consistent.

2022-08-23 13:33 UTC, devkonrad commented
> @devkonrad Looks good! Could you check if the font size on the button text is the same font size as the button text on the sign in and register pages? I'd like them to be consistent.

Hi, @dboyer! I had the impression that the button font size was bigger than the sign up, too. But i used the exact same class, I guess that its a optcal illusion because here we have more text than the sign up screen.

2022-08-23 13:36 UTC, dboyer commented
Interesting! That makes sense that the amount of text could fool the eye. Thanks for checking!

2022-08-24 14:58 UTC, viviancan requested changes
Hey Alex! Thx for tackling this one! I am leaving one comment on the ticket about the font for the "Email" label! Besides that, it looks good!

2022-08-24 14:59 UTC, viviancan commented
The "email" label font should match the updated font like on the sign-in page. I think this is our old branding font :) 
![CleanShot 2022-08-24 at 09 54 28@2x](https://user-images.githubusercontent.com/29210380/186452309-4c9c9dc0-3814-411a-ad6f-344aa81d5aa7.png)

2022-08-24 15:59 UTC, devkonrad commented
> @devkonrad The "email" label font should match the updated font like on the sign-in page. I think this is our old branding font :) ![CleanShot 2022-08-24 at 09 54 28@2x](https://user-images.githubusercontent.com/29210380/186452309-4c9c9dc0-3814-411a-ad6f-344aa81d5aa7.png)
> 
> Example below ![CleanShot 2022-08-24 at 10 01 25@2x](https://user-images.githubusercontent.com/29210380/186453035-2927e7b8-003d-421a-a66c-877966494772.png)

Good caught, @viviancan ! I will fix it! ;)

2022-08-25 20:48 UTC, shaunxp20 commented on app/views/password_resets/new.html.erb
> +<% provide :main_header, render('application/templates/tg_green_header', heading: "Welcome Back") %>
I tried this one locally and I was able to reset a password! 👍 The one thing popping to me is this header "Welcome Back", maybe that should say something else for the password reset page? 🤔  @dboyer

2022-08-26 13:40 UTC, dboyer commented on app/views/password_resets/new.html.erb
> +<% provide :main_header, render('application/templates/tg_green_header', heading: "Welcome Back") %>
Hmmmm.......good question. It's not the best fit but I'm also not coming up with anything better so let's keep it as "welcome back" for now. Probably if they are resetting a password they've been on the site at least once so it's not _wrong_ to welcome them back, just not expected.

2022-08-31 19:58 UTC, shaunxp20 approved these changes

2022-08-31 21:45 UTC, devkonrad commented
> > @devkonrad The "email" label font should match the updated font like on the sign-in page. I think this is our old branding font :) ![CleanShot 2022-08-24 at 09 54 28@2x](https://user-images.githubusercontent.com/29210380/186452309-4c9c9dc0-3814-411a-ad6f-344aa81d5aa7.png)
> > Example below ![CleanShot 2022-08-24 at 10 01 25@2x](https://user-images.githubusercontent.com/29210380/186453035-2927e7b8-003d-421a-a66c-877966494772.png)
> 
> Good caught, @viviancan ! I will fix it! ;)

Fixed it yet, @viviancan! :)

2022-09-02 17:23 UTC, merged